const EMAIL_MUST_BE_VALID_ERROR_MESSAGE = 'Email must be valid';
const PASSWORD_MUST_BE_BETWEEN_4_and_20_CHARACTERS_ERROR_MESSAGE =
  'Password must be between 4 and 20 characters';
const EMAIL_IS_ALREADY_IN_USE_ERROR_MESSAGE = 'Email is already in use';
const YOU_MUST_SUPPLY_A_PASSWORD_ERROR_MESSAGE = 'You must supply a password';
const INVALID_CREDENTIALS = 'Invalid credentials';

export {
  EMAIL_MUST_BE_VALID_ERROR_MESSAGE,
  PASSWORD_MUST_BE_BETWEEN_4_and_20_CHARACTERS_ERROR_MESSAGE,
  EMAIL_IS_ALREADY_IN_USE_ERROR_MESSAGE,
  YOU_MUST_SUPPLY_A_PASSWORD_ERROR_MESSAGE,
  INVALID_CREDENTIALS,
};
